language: node_js
    - "8"
install:
    - npm cache rm --force
    - npm install
services:
    - postgresql
# cache:
#     directories:
#         - "node_modules"
script: npm run test:api
before_script:
    - psql -c "CREATE DATABASE eventsmanager_test;" -U postgres
    - npm install nyc coveralls codeclimate-test-reporter codecov -g
after_script:
    - nyc report --reporter=text-lcov | coveralls
    - codeclimate-test-reporter < ./coverage/lcov.info
    - npm run test:client
    - codecov
